from pymongo import MongoClient

life=MongoClient("mongodb://localhost:27017/")
db=life["Product_Finder"]
collection=db["Details"]

collection.delete_many({})

data=[
    {
        "name" : "Panasoinc g87 QLED",
        "brand" : "Panasonic",
        "price" : 44000,
        "displayresolution" : "1080p/Full HD",
        "models" : "QLED",
        "inches" : "43 inches",
        "connectivity" : "Wi-fi",
        "os" : "Android",
        "image" : "pana2.webp",
        "rating" : 3.6,
        "stock" : "No Products Are Available",
        "description" : "Experience true-to-life visuals with Panasonic TV, designed to deliver natural colors and detailed clarity. With immersive sound and smart functionality, it offers a refined and dependable entertainment experience.",
    },
    {
        "name" : "Sony BRAVIA 2M2 Series",
        "brand" : "SONY",
        "price" : 37000,
        "displayresolution" : "4K/Ultra HD",
        "models" : "OLED",
        "inches" : "32 inches",
        "connectivity" : "Wi-fi",
        "os" : "Google TV",
        "image" : "sony1.webp",
        "rating" : 4.8,
        "stock" : 3,
        "description" : "Experience stunning visuals and immersive sound with Sony TV, designed to bring cinema-quality entertainment into your home. Powered by advanced picture processing technology, it delivers vibrant colors, sharp contrast, and crystal-clear clarity",
    },
    {
        "name" : "Samsung QBK",
        "brand" : "Samsung",
        "price" : 49800,
        "displayresolution" : "4K/Ultra HD",
        "models" : "OLED",
        "inches" : "27 inches",
        "connectivity" : "Wi-fi",
        "os" : "Google TV",
        "image" : "sam1.webp",
        "rating" : 3.3,
        "stock" : 10,
        "description" : "Samsung TV delivers exceptional picture quality with vibrant colors, sharp contrast, and smooth motion. Powered by advanced display technology and smart features, it provides seamless access to streaming apps and connected devices. Its sleek design enhances any modern living space.",
    },
    {
        "name" : "Panasoinc s65",
        "brand" : "Panasonic",
        "price" : 65000,
        "displayresolution" : "720p/HD",
        "models" : "LCD",
        "inches" : "16 inches",
        "connectivity" : "Wi-fi",
        "os" : "Google TV",
        "image" : "pana3.webp",
        "rating" : 3.9,
        "stock" : 8,
        "description" : "Panasonic TV offers stable performance, clear visuals, and long-lasting quality. It’s a trusted choice for families looking for dependable home entertainment.",
    },
    {
        "name" : "Sony BRAVIA 1G1 Series",
        "brand" : "SONY",
        "price" : 120000,
        "displayresolution" : "4K/Ultra HD",
        "models" : "LCD",
        "inches" : "55 inches",
        "connectivity" : "Wi-fi",
        "os" : "Google TV",
        "image" : "sony3.webp",
        "rating" : 4.6,
        "stock" : 5,
        "description" : "Sony TV offers clear picture quality, smooth performance, and easy-to-use smart features for everyday entertainment. Watch movies, sports, and shows with enhanced clarity and realistic sound. With reliable performance and a stylish design.",
    },
    {
        "name" : "Panasonic h3",
        "brand" : "Panasonic",
        "price" : 265000,
        "displayresolution" : "4K/Ultra HD",
        "models" : "QLED",
        "inches" : "27 inches",
        "connectivity" : "Wi-fi",
        "os" : "Web OS",
        "image" : "pana1.webp",
        "rating" : 4.2,
        "stock" : 2,
        "description" : "Panasonic TV is known for its reliable performance, accurate color reproduction, and clear picture quality. Built with durable components and smart features, it delivers consistent and comfortable viewing for all types of content.",
    },
    {
        "name" : "Xiamoi UAC Series",
        "brand" : "Xiaomi",
        "price" : 26750,
        "displayresolution" : "4K/Ultra HD",
        "models" : "LCD",
        "inches" : "16 inches",
        "connectivity" : "Bluetooth",
        "os" : "Google TV",
        "image" : "xia1.webp",
        "rating" : 4.8,
        "stock" : 10,
        "description" : "Xiaomi TV combines high-quality display performance with smart Android features at great value. With vivid colors, smooth visuals, and built-in streaming support, it ensures an enjoyable and convenient entertainment experience.",
    },
    {
        "name" : "Samsung AK",
        "brand" : "Samsung",
        "price" : 54300,
        "displayresolution" : "1080p/Full HD",
        "models" : "OLED",
        "inches" : "43 inches",
        "connectivity" : "Bluetooth",
        "os" : "Android",
        "image" : "sam2.webp",
        "rating" : 4.4,
        "stock" : "No Products Are Available",
        "description" : "Enjoy a next-level viewing experience with Samsung TV, featuring brilliant visuals, immersive sound, and smart connectivity. From movies to gaming, every scene feels more realistic with Samsung’s powerful processing and elegant design.",
    },
    {
        "name" : "Xiaomi GF Series",
        "brand" : "Xiaomi",
        "price" : 73000,
        "displayresolution" : "1080p/Full HD",
        "models" : "LCD",
        "inches" : "55 inches",
        "connectivity" : "Wi-fi",
        "os" : "Android",
        "image" : "xia2.webp",
        "rating" : 4.2,
        "stock" : 6,
        "description" : "Upgrade your home entertainment with Xiaomi TV, offering stunning visuals, powerful sound, and smart features in a sleek design. Enjoy unlimited content with easy access to popular apps and voice control support.",
    },
    {
        "name" : "Sony BRAVIA 3S4 Series",
        "brand" : "SONY",
        "price" : 57000,
        "displayresolution" : "1080p/Full HD",
        "models" : "LED",
        "inches" : "27 inches",
        "connectivity" : "Bluetooth",
        "os" : "Android",
        "image" : "sony2.webp",
        "rating" : 4.4,
        "stock" : "No Products Are Available",
        "description" : "Upgrade your entertainment with Sony TV, where brilliant picture quality meets powerful sound. Enjoy lifelike visuals, deep blacks, and rich colors that make every scene come alive",
    },
    {
        "name" : "Xiaomi II6 Series",
        "brand" : "Xiaomi",
        "price" : 135000,
        "displayresolution" : "720p/HD",
        "models" : "LCD",
        "inches" : "55 inches",
        "connectivity" : "Wi-fi",
        "os" : "Web OS",
        "image" : "xia3.webp",
        "rating" : 4.9,
        "stock" : 8,
        "description" : "Xiaomi TV provides good picture quality, smart connectivity, and smooth performance. It’s a budget-friendly choice for everyday entertainment and online streaming.",
    },
    {
        "name" : "Samsung E38",
        "brand" : "Samsung",
        "price" : 80000,
        "displayresolution" : "720p/HD",
        "models" : "OLED",
        "inches" : "55 inches",
        "connectivity" : "Wi-fi",
        "os" : "Web OS",
        "image" : "sam3.webp",
        "rating" : 4.1,
        "stock" : 6,
        "description" : "Samsung TV offers clear visuals, fast performance, and easy-to-use smart features. It’s ideal for watching movies, shows, and sports with reliable quality and a stylish look.",
    },
    
]

collection.insert_many(data)
print("Database la insert agiruchu!!!!!")